### ISSUE TITLE
Max file size field cannot take more than 999

### ISSUE THREAD

**Issue by michaelmcneela** [Kevin-De-Koninck/Get-It#11]
Setting the max file size larger than 999 causes youtube-dl to complain about an invalid number. I believe this may be because macOS's number input field adds a comma ("99,999") to thousands, and possibly higher numbers, which may be being passed - as a string including that comma - to youtube-dl?

Also, 
- the default max file size of 15MB seems too small for most uses, especially for video downloads (versus audio downloads)
- there doesn't seem to be a need for a max file size?

**Comment by Kevin-De-Koninck** [comment]
I think the reason for the max file size was:
When I converted my spotify playlist to a youtube playlist (to be able to download them), Some playlists also included mixes of more than an hour, something you don't want in a playlist of only songs. That's why I added a limit of 15MB (which seemed fine at that time).

I'll update the default value to none (unlimitted) and fix the max size issue when I got some spare times on my hands.

**Comment by michaelmcneela** [comment]
Ah, that makes sense.

(Thanks for making a nice, open-source GUI wrapper! 👌🏼)

**Comment by Kevin-De-Koninck** [comment]
Late to the party... Broke my hand last night so now I got the time! I'm sorry for the long wait. I'll be fixing most issues in the coming days (as many as I can).

**Comment by Kevin-De-Koninck** [comment]
@michaelmcneela A new version of Get It will be available shortly (will bump this issue), can you retest this and report you findings?

```
settingsDict["maxFileSize"] = maxFileSize.stringValue.replacingOccurrences(of: ".", with: "").replacingOccurrences(of: ",", with: "")
```
The code already replaces commas and dots, so I'm not seeing the same problem as you.

If you have the same error, can you please provide me the output of `cat /tmp/getit_logs`?

Thanks!

**Comment by Kevin-De-Koninck** [comment]
New version available here:
https://github.com/Kevin-De-Koninck/Get-It/releases/tag/v0.7
